name: Makefile CI

on:
  push:
    branches: ["nightly", "dev", "beta", "stable"]
  pull_request:
    branches: ["nightly", "dev", "beta", "stable"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang nasm make xorriso git

      - name: Test Kernel
        run: make test
